export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";

export const GET_PROJECT = "GET_PROJECT";
export const  UPDATE_PROJECT = "UPDATE_PROJECT";
export const  DELETE_PROJECT = "DELETE_PROJECT";


/***ERROR ACTION TYPE */
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";
export const GET_ALL_PROJECTS_ERROR = "GET_ALL_PROJECTS_ERROR";
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR";

export const  UPDATE_ERROR = "UPDATE_ERROR";
export const  DELETE_ERROR = "DELETE_ERROR";

/**
 * UPLOAD DOCUMENT
 */
export const ADD_DOCUMENT_STARTED = "ADD_DOCUMENT_STARTED";
export const ADD_DOCUMENT_COMPLETED = "ADD_DOCUMENT_COMPLETED";
export const ADD_DOCUMENT_ERROR = "ADD_DOCUMENT_ERROR";

